apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplenode-deployment
  labels:
    app: simplenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenode
  template:
    metadata:
      labels:
        app: simplenode 
    spec:
      containers:
      - name: simplenode
        image: joaquimdelmonte/simplenode:v1
        ports:
        - containerPort: 3000
