apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # Port accessible depuis l'extérieur du cluster
  type: NodePort  # Changer de ClusterIP à NodePort
