# Utilisez une image officielle Node.js comme base
FROM node:14

# Répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copiez les fichiers package.json et package-lock.json
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste des fichiers de l'application
COPY . .

# Exposez le port sur lequel votre application écoute
EXPOSE 3000

# Démarrez l'application
CMD ["node", "app.js"]
