apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplenode-deployment
  labels:
    app: simplenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenode
  template:
    metadata:
      labels:
        app: simplenode 
    spec:
      containers:
      - name: simplenode
        image: joaquimdelmonte/simplenode:v8
        ports:
        - containerPort: 3000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: database
