apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: Um9vdFBhc3N3b3Jk   # "RootPassword" encodé en base64
  username: bXl1c2Vy               # "myuser" encodé en base64
  password: TXlVc2VyUGFzc3dvcmQ=   # "MyUserPassword" encodé en base64
  database: dGFza3NEQg==           # "tasksDB" encodé en base64
